// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4DlOOxTNUHn9FPZxusaTSo2f99_qzLTs',
    appId: '1:127009020167:web:6a986d53d268716092cda2',
    messagingSenderId: '127009020167',
    projectId: 'salao-pro-app',
    authDomain: 'salao-pro-app.firebaseapp.com',
    storageBucket: 'salao-pro-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASy7a2q-aZ0qaKlZ0ieCg1_y16da9vjgU',
    appId: '1:127009020167:android:984665494732382292cda2',
    messagingSenderId: '127009020167',
    projectId: 'salao-pro-app',
    storageBucket: 'salao-pro-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMde0iDwEc3eNNaMm_TJ46Mn2uIjhvgi0',
    appId: '1:127009020167:ios:5365271c96517f3c92cda2',
    messagingSenderId: '127009020167',
    projectId: 'salao-pro-app',
    storageBucket: 'salao-pro-app.firebasestorage.app',
    iosBundleId: 'com.example.appSalaoPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMde0iDwEc3eNNaMm_TJ46Mn2uIjhvgi0',
    appId: '1:127009020167:ios:5365271c96517f3c92cda2',
    messagingSenderId: '127009020167',
    projectId: 'salao-pro-app',
    storageBucket: 'salao-pro-app.firebasestorage.app',
    iosBundleId: 'com.example.appSalaoPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4DlOOxTNUHn9FPZxusaTSo2f99_qzLTs',
    appId: '1:127009020167:web:a7375ee759b992a892cda2',
    messagingSenderId: '127009020167',
    projectId: 'salao-pro-app',
    authDomain: 'salao-pro-app.firebaseapp.com',
    storageBucket: 'salao-pro-app.firebasestorage.app',
  );
}
